### ISSUE TITLE
Figure out the budget

### ISSUE THREAD

**Issue by zimbatm** [nixcon/2023.nixcon.org#10]
There is a rought budget now, still pending "approval" at the next meeting.

![Image](https://user-images.githubusercontent.com/638836/220958570-46e76463-ef6c-499d-aacd-ae384fcb2105.png)

**Comment by andir** [comment]
The budget we drafted is visible here: https://docs.google.com/spreadsheets/d/1FLIy-CTgWw2Wukzc81Ql9ULhtIid5Bq5AjFK6K504Sc/edit
