### ISSUE TITLE
Room photos

### ISSUE THREAD

**Issue by mweinelt** [nixcon/2023.nixcon.org#12]
The three smaller rooms downstairs:
https://github.com/nixcon/2023.nixcon.org/issues/12#issuecomment-1442228089
https://github.com/nixcon/2023.nixcon.org/issues/12#issuecomment-1442229270
https://github.com/nixcon/2023.nixcon.org/issues/12#issuecomment-1442230668

The big lecture hall upstairs:
https://github.com/nixcon/2023.nixcon.org/issues/12#issuecomment-1442231053

**Comment by mweinelt** [comment]
S105/22

![S105 Raum 22](https://user-images.githubusercontent.com/131599/220996016-dae1f1e8-1687-493a-94cd-b74c1d9f9b74.jpeg)
![S105 Raum 22 (3)](https://user-images.githubusercontent.com/131599/220996023-ffad365e-cc7f-40e9-8be3-d435d3730add.jpeg)
![S105 Raum 22 (4)](https://user-images.githubusercontent.com/131599/220996028-940b4b34-8fc5-4765-8812-02816a4c27ee.jpeg)

**Comment by mweinelt** [comment]
S105/23

![S105 Raum 23](https://user-images.githubusercontent.com/131599/220996201-744b7112-4a9d-4466-9937-e08399eb090a.jpeg)
![S105 Raum 23 (2)](https://user-images.githubusercontent.com/131599/220996213-e0cfda3a-1837-4916-9f03-569f3b7abb6d.jpeg)
![S105 Raum 23 (3)](https://user-images.githubusercontent.com/131599/220996219-13448755-f0d6-4f71-b5ae-5d9b8a36dc66.jpeg)

**Comment by mweinelt** [comment]
S105/24

![S105_Seminarraum-hinten](https://user-images.githubusercontent.com/131599/220996428-3f8b3dea-c946-4760-8281-4438a99c30d1.jpg)
![S105_Seminarraum-vorne](https://user-images.githubusercontent.com/131599/220996434-988f0caa-1267-4c34-bbe1-c00410e356cd.jpg)

**Comment by mweinelt** [comment]
The big lecture room.

S105/122

![S105_122h](https://user-images.githubusercontent.com/131599/220995822-d6e3c9ff-423b-47df-a77a-468aecd134b6.jpg)
![S105_122hl](https://user-images.githubusercontent.com/131599/220995826-60c02f8e-ebe2-41e6-a1f7-ef6249b8d670.jpg)
![S105_122hr](https://user-images.githubusercontent.com/131599/220995829-fc1741a7-a5d0-420f-8cf5-922ed48ff093.jpg)
![S105_122v](https://user-images.githubusercontent.com/131599/220995832-320ecc7b-69c7-4467-b8e8-daa9b4c171ed.jpg)
![S105_122vl](https://user-images.githubusercontent.com/131599/220995833-e1e5b531-bc34-419e-b039-a096f2652711.jpg)
![S105_122vr](https://user-images.githubusercontent.com/131599/220995836-1cf53694-3bc6-47df-939e-59b764a3767d.jpg)

**Comment by fleaz** [comment]
FYI: There are official websites from the university for every room, which include some metadata (like e.g. seat count, sqm, accessibility) and some nice pictures:


[S105|22](https://www.tucan.tu-darmstadt.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-A-9hcxUqln3fU011i77DPzh1CpmDEgKx5PHZ4hEljLTJ372WV6C1l96BR0pDRDXPo4Xc8XYX11CwP5rLPhKj8QbMACJh46gbv2MXVTk8e6K6TJz29cu7WPCw7NRJkd-3SdPsxqk8gK2eps-D89tYZvupZOSFtg-SsSX26vr9Pznkzi10_)
[S105|23](https://www.tucan.tu-darmstadt.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-AfgwE2zemSuXsmBNGqM35sqTPAt3cIv1MVK-efYGFw2AvGbBpXCdBIBQ3k~fMK3YuiYW00YHpKNZZCTTBZ5Gf58HlrcwPzzsijSPQ8VkWc9R3UbEgfObqOwh~ZQ6vZtN-oJx5iZg1S7MhQzqMa89G8loaEOwpei67ofKAnHYFqnEVjC4_)
[S105/24](https://www.tucan.tu-darmstadt.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-AK1z1ktAeM0aotFiJDTuyKjrucc7NzNqbWzAF2vNkjOSJmZPQH8Dq4IdtX0pRfC8t9qSKRKa7j3CxO6Ed7DeV5ARznTWM2iXe0caZHaBksKbFxPVjbHRWzBKCDnUCj4R4rx3PeRDE3ByVuRR3DsPJ9JYMaBGd3wkG8LyG2nc-nM2qiWQ_)
[S105|122](https://www.tucan.tu-darmstadt.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-ATJ31SrKFzT40ovVTmwcbWo5QnFPeyEfOrlAmuBByHWnhVBf1ar5WoWTHyiT41n~0i1GTn6KG1VxC~kEUbMKqGoxaw-JSdjc3~L5FsBZOfdbiFwn-fufMmBN7HWnz337NVCzc~zTTsXc5LZ12qcGib81PLFLsCSBM6LXW0hmBSGgARZs_)
