### ISSUE TITLE
Swag

### ISSUE THREAD

**Issue by andir** [nixcon/2023.nixcon.org#15]
* Who does the art?
    * community call for art/logo?
    * Avocadoom & megfault are willing to do some work for the website, we can likely piggy back on the logo variant they come up with

* [ ] T-Shirts cost somewhere between 10 and 25€ I guess? Where do we get them? What do we put on them? Who does the art?
    * Freddruck
    * MRMCD gets their T-Shirts from Caritas, 5.79€ + 7% tax + printing mask (each ~20€)
        * 18€ per shirt all in all, front and back printed
        * braack has contact details

* [ ] Mugs probably are around 5-8€ each. What do we want to print on them?
    * Flokli might have an old invoice
    * flyeralarm

**Comment by andir** [comment]
@megfault can you come up with some logo for the T-Shirts and mugs?

**Comment by megfault** [comment]
Yup, let's discuss details offline.

**Comment by refroni** [comment]
Ross (one of our amazing folks on the flox team) is making some amazing gifts (hand/robot/Ross made). Mentioned it to @andir / hexa on the call last week.

**Comment by rossturk** [comment]
Here is a quick video showing the Nix Brix that I'm making for speakers: https://www.youtube.com/watch?v=oy8asKWcjLY

**Comment by mweinelt** [comment]
250 tote bags have been ordered and already payed for.

https://pema-verpackung.de/de/produkte/tragetaschen/baumwolltragetaschen/unbedruckte-lagerware
