### ISSUE TITLE
Walk through the venue

### ISSUE THREAD

**Issue by andir** [nixcon/2023.nixcon.org#17]
We should do a walk-through of the venue to note and talk about some things.

Things to talk about:

 * [ ] Room division (where will be food, chatting, talks, hacking, ...)
 * [ ] AV Setup & requirements check (probably with someone from the VOC @hexchen ?!?)
 * [ ] Take pictures of all the rooms, hallways, blueprints, ... we should document as much as we might need during the further preparation
 * [ ] What else?!?

**Comment by andir** [comment]
@mweinelt can you put your pictures here?

**Comment by mweinelt** [comment]
They're over here: https://github.com/nixcon/2023.nixcon.org/issues/12
