### ISSUE TITLE
Announce location and dates

### ISSUE THREAD

**Issue by zimbatm** [nixcon/2023.nixcon.org#2]
This also includes dates for CFP (which traditionally ends a month or earlier and then is extended).

**Comment by yater** [comment]
#5#[issuecomment-1502101589](/nixcon/2023.nixcon.org/issues/5#issuecomment-1502101589)

**Comment by andir** [comment]
We have locaction and date secured. Will draft an announcement soon.

**Comment by andir** [comment]
See for details: https://github.com/nixcon/2023.nixcon.org/issues/5#issuecomment-1567437387

**Comment by mweinelt** [comment]
https://discourse.nixos.org/t/nixcon-2023-darmstadt-germany/29466?u=hexa
