### ISSUE TITLE
Contact the sponsors

### ISSUE THREAD

**Issue by zimbatm** [nixcon/2023.nixcon.org#3]

**Comment by refroni** [comment]
Adding few more sponsorship items (please move/let me know if this isn't the right issue)

- [ ] Draft sponsorship tiers, post on site/discourse/anywhere relevant
- [ ] Draft sponsorship comms/messaging and then post

**Comment by refroni** [comment]
Example of sponsor tier plan from 2022 if helpful -> https://docs.google.com/document/d/1At1JAWp5b31rkjjsgqQf_pFY4mwqcbcqvD0D4wbo6jQ/edit
