### ISSUE TITLE
Lock in the Venue and dates

### ISSUE THREAD

**Issue by zimbatm** [nixcon/2023.nixcon.org#5]

**Comment by andir** [comment]
The venue dates are being confirmed with the university. As discussed they open registration only relatively shortly before the actual semster. Hoping to get a confirmation soon.

**Comment by yater** [comment]
BTW: 2023-09-15 -17 the [C3D2](https://c3d2.de/) will having the [Datenspuren (2023)](https://datenspuren.de/2023/) event. (It is happening every year from Friday till Sunday of week 37 (W37-5 -7).)

**Comment by andir** [comment]
Dates: 2023-09-08 to 2023-09-10 23:00 CEST.
Location: 
```
    City:
    Darmstadt, Germany
    Location:
    TU-Darmstadt, S1|05 Machinenhaus
    Full Address:
    Magdalenenstr. 12, 64289 Darmstadt

https://goo.gl/maps/8g5xKAsZpsXAwLXP8
```

**Comment by Kranzes** [comment]
Will there also be a hackathon on the 11th like there was in the last NixCon?
