### ISSUE TITLE
Contact C3VOC

### ISSUE THREAD

**Issue by zimbatm** [nixcon/2023.nixcon.org#9]
https://c3voc.de/wiki/howto:veranstalter
https://c3voc.de/wiki/requirements

**Comment by mweinelt** [comment]
![voc-register](https://user-images.githubusercontent.com/131599/221000146-6f75d3d4-587a-4ab4-ba6e-8aa82a55ea43.png)

**Comment by mweinelt** [comment]
https://c3voc.de/wiki/events:nixcon2023

**Comment by mweinelt** [comment]
Received an email, that they set the event to confirmed and plan to bring two cases.

**Comment by mweinelt** [comment]
Sent an update on the changed date arrangements, and they appear to be no problem.

@hexchen is our contact, and they want to join up, when we plan to inspect the venue. This will likely be on a weekday, when the rooms are open anyway, as we don't have anyone who can unlock the rooms.
